//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;


public class Ennemi_pizza : Ennemi
{
	void Start()
	{
		base.Start ();

		_speed = 0.5f;
		timeToAttack = 15f;
	}

	void Update()
	{
		base.Update ();


	}
}
