//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class Ennemi_beignet : Ennemi
{
	public Ennemi_beignet ()
	{}

	void Start()
	{
		base.Start ();

		_horizontal_pos = Random.Range (0.0f, 5.0f);
		boundTop = Random.Range (2.0f, 5.0f);
		boundDown = Random.Range (-3.0f, -2.0f);
	}
}
