//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections;

public class Ennemy_kamikaze : Ennemi
{
	const float DEADZONE = 1.5f;

	public Ennemy_kamikaze ()
	{

	}


	void Start()
	{
		base.Start ();

		_speed = 6.0f;
		_horizontal_pos = -15.0f;
		_onlyHorizontal = true;
	}


	void Update()
	{
		base.Update ();

		Player player = GameObject.Find("Player").GetComponent<Player> ();
		
		if (player != null)
		{
			float translate = 3.0f * Time.deltaTime;

			if(player.transform.position.y < transform.position.y - (DEADZONE + Random.Range(0.0f, 1f)))
			{
				transform.Translate(new Vector3(0, -translate, 0));
			}
			else if(player.transform.position.y > transform.position.y + (DEADZONE + Random.Range(0.0f, 1f)))
			{
				transform.Translate(new Vector3(0, translate, 0));
			}
		}
	}
}


