//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class Movements  : MonoBehaviour
{
	protected float SPEED = 3.0f;
	protected Vector3 _movementToApply;
	
	protected void initMovement()
	{
		_movementToApply = new Vector3 ();
	}
	
	protected void moveUp()
	{
		_movementToApply.y += 1;
	}
	
	protected void moveDown()
	{
		_movementToApply.y += -1;
	}
	
	protected void moveLeft()
	{
		_movementToApply.x += -1;
	}
	
	protected void moveRight()
	{
		_movementToApply.x += 1;
	}
	
	
	protected void moveHorizontal(float movement)
	{
		_movementToApply.x = movement;
	}
	
	
	protected void moveVertical(float movement)
	{
		_movementToApply.y = -movement;
	}
	
	
	protected void applyMovement()
	{
		Vector3 movementWithSpeed = _movementToApply * SPEED;
		movementWithSpeed *= Time.deltaTime;
		transform.Translate (movementWithSpeed);
	}
}

