//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class Projectile : MonoBehaviour
{
	float SPEED = 20f;
	bool _isfire;

	public Projectile ()
	{
		_isfire = false;
	}

	public void startFire()
	{
		_isfire = true;
	}


	void Start()
	{
	}


	void Update()
	{
		if (_isfire)
		{
			Vector3 movementWithSpeed = new Vector3(SPEED, 0, 0);
			movementWithSpeed *= Time.deltaTime;
			transform.Translate (movementWithSpeed);
		}
	}
}
